surveyEngineOptions({
	'clickableimages':{
		'rowBtnBckgrndColorDown' : 0xffffff,
		'rowContainBorderColor' : 0xa6a8ab,
		'rowContainBckgrndColor' : 0xffffff,
		'rowBtnBckgrndColorUp' : 0xffffff,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'tooltipBorderColor' : 0xa6a8ab,
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xffffff,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xd2d3d5,
		'rowBtnBorderColorOver' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x9fcc3b,
		'rowBtnBckgrndColorOver' : 0xffffff,
		'rowBtnLabelColorOver' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'rowRadChckLabelColorUp' : 0x5b5f65,
		'rowRadChckLabelColorOver' : 0x5b5f65,
		'rowRadChckLabelColorDown' : 0x5b5f65,
		'rowKntrInputLabelColorUp' : 0x555555,
		'rowKntrInputLabelColorOver' : 0x000000,
		'rowKntrInputLabelColorDown' : 0x000000,
		'rowOtherInputColor' : 0x5b5f65,
		'zoomGalleryBorderColor' : 0xa6a8ab
	},
	'qcbtnmatrix':{
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'rowBtnBckgrndColorDown' : 0xffbd1a,
		'rowContainBorderColor' : 0xa6a8ab,
		'rowContainBckgrndColor' : 0xffffff,
		'rowBtnBckgrndColorUp' : 0xf2f2f2,
		'colContainBorderColor' : 0xa6a8ab,
		'colContainBckgrndColor' : 0xffffff,
		'tooltipBorderColor' : 0xa6a8ab,
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xffffff,
		'colBtnBckgrndColorUp' : 0xffffff,
		'colBtnBckgrndColorOver' : 0xf2f2f2,
		'colBtnBckgrndColorDown' : 0xffbd1a,
		'colBtnLabelColorUp' : 0x5b5f65,
		'colBtnLabelColorOver' : 0x5b5f65,
		'colBtnLabelColorDown' : 0x5b5f65,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'colContainLabelColor' : 0x5b5f65,
		'colBtnBorderColorUp' : 0xd2d3d5,
		'colBtnBorderColorOver' : 0xa6a8ab,
		'colBtnBorderColorDown' : 0xffbd1a,
		'colBtnLabelOverlayBckgrndColor' : 0xffffff,
		'colRadChckLabelColorUp' : 0x5b5f65,
		'colRadChckLabelColorOver' : 0x5b5f65,
		'colRadChckLabelColorDown' : 0x5b5f65,
		'colKntrInputLabelColorUp' : 0x5b5f65,
		'colKntrInputLabelColorOver' : 0x5b5f65,
		'colKntrInputLabelColorDown' : 0x5b5f65,
		'colOtherInputColor' : 0x5b5f65
	},
	'qcbtnmatrixgrid':{
		'rowBtnLabelColorUp': 0x555555,
		'rowBtnLabelColorDown': 0x555555,
		'zoomOverlayBckgrndColor': 0x000000,
		'colContainBorderColor': 0xcccccc,
		'colContainBckgrndColor': 0xffffff,
		'tooltipBorderColor': 0xcccccc,
		'tooltipBckgrndColor': 0xf5f5f5,
		'tooltipFontColor': 0x555555,
		'zoomBorderColor': 0xcccccc,
		'zoomBckgrndColor': 0xf5f5f5,
		'colBtnBckgrndColorUp': 0xf5f5f5,
		'colBtnBckgrndColorOver': 0x9FCC3B,
		'colBtnBckgrndColorDown': 0x9FCC3B,
		'colBtnLabelColorUp': 0x555555,
		'colBtnLabelColorOver': 0xffffff,
		'colBtnLabelColorDown': 0xffffff,
		'colBtnBorderColorOver': 0x9FCC3B,
		'colBtnBorderColorDown': 0x9FCC3B,
		'rowBtnLabelBckgrndColor': 0xf2f2f2,
		'colBtnLabelBckgrndColor': 0xf2f2f2,
		'rowBtnBckgrndColorDown': 0xfce6c9,
		'rowContainBorderColor': 0xcccccc,
		'rowContainBckgrndColor': 0xf5f5f5,
		'rowBtnBorderColor': 0xcccccc,
		'rowBtnBckgrndColorUp': 0xf5f5f5,
		'colBtnBorderColor': 0xcccccc,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'colContainLabelColor' : 0x5b5f65,
		'colBtnBorderColorUp' : 0xd2d3d5,
		'colBtnLabelOverlayBckgrndColor' : 0xffffff,
		'colRadChckLabelColorUp' : 0x5b5f65,
		'colRadChckLabelColorOver' : 0x5b5f65,
		'colRadChckLabelColorDown' : 0x5b5f65,
		'colKntrInputLabelColorUp' : 0x5b5f65,
		'colKntrInputLabelColorOver' : 0x5b5f65,
		'colKntrInputLabelColorDown' : 0x5b5f65,
		'colOtherInputColor' : 0x5b5f65
	},
	'qcbtnmatrixgridset':{
		'rowBtnLabelColorUp': 0x555555,
		'rowBtnLabelColorDown': 0x555555,
		'zoomOverlayBckgrndColor': 0x000000,
		'colContainBorderColor': 0xcccccc,
		'colContainBckgrndColor': 0xffffff,
		'tooltipBorderColor': 0xcccccc,
		'tooltipBckgrndColor': 0xf5f5f5,
		'tooltipfontColor': 0x555555,
		'zoomBorderColor': 0xcccccc,
		'zoomBckgrndColor': 0xf5f5f5,
		'colBtnBckgrndColorUp': 0xf5f5f5,
		'colBtnBckgrndColorOver': 0x9FCC3B,
		'colBtnBckgrndColorDown': 0x9FCC3B,
		'colBtnLabelColorUp': 0x333333,
		'colBtnLabelColorOver': 0xffffff,
		'colBtnLabelColorDown': 0xffffff,
		'colBtnBorderColorOver': 0x9FCC3B,
		'colBtnBorderColorDown': 0x9FCC3B,
		'rowBtnLabelBckgrndColor': 0xf2f2f2,
		'colBtnLabelBckgrndColor': 0xf2f2f2,
		'rowBtnBckgrndColorDown': 0xfce6c9,
		'rowContainBorderColor': 0xcccccc,
		'rowContainBckgrndColor': 0xf5f5f5,
		'rowBtnBorderColor': 0xcccccc,
		'rowBtnBckgrndColorUp': 0xf5f5f5,
		'colBtnBorderColor': 0xcccccc,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'colContainLabelColor' : 0x5b5f65,
		'colBtnBorderColorUp' : 0xd2d3d5,
		'colBtnLabelOverlayBckgrndColor' : 0xffffff,
		'colRadChckLabelColorUp' : 0x5b5f65,
		'colRadChckLabelColorOver' : 0x5b5f65,
		'colRadChckLabelColorDown' : 0x5b5f65,
		'colKntrInputLabelColorUp' : 0x5b5f65,
		'colKntrInputLabelColorOver' : 0x5b5f65,
		'colKntrInputLabelColorDown' : 0x5b5f65,
		'colOtherInputColor' : 0x5b5f65
	},
	'dynamicgrid':{
		'rowBtnBckgrndColorDown' : 0xffffff, 
		'rowContainBorderColor' : 0xa6a8ab,
		'rowContainBckgrndColor' : 0xffffff,
		'rowBtnBckgrndColorUp' : 0xffffff,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'tooltipBorderColor' : 0xa6a8ab,
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xffffff,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xd2d3d5,
		'rowBtnBorderColorDown' :  0xd2d3d5,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'colContainBorderColor' : 0xa6a8ab,
		'colContainBckgrndColor' : 0xffffff,
		'colBtnBckgrndColorUp' : 0xffffff,
		'colBtnBckgrndColorOver' : 0xf2f2f2,
		'colBtnBckgrndColorDown' : 0x9FCC3B,
		'colBtnLabelColorUp' : 0x5b5f65,
		'colBtnLabelColorOver' : 0x5b5f65,
		'colBtnLabelColorDown' : 0xffffff,
		'colContainLabelColor' : 0x5b5f65,
		'colBtnBorderColorUp' : 0xd2d3d5,
		'colBtnBorderColorOver' : 0xa6a8ab,
		'colBtnBorderColorDown' : 0x5b5f65,
		'colBtnLabelOverlayBckgrndColor' : 0xffffff,
		'colRadChckLabelColorUp' : 0x5b5f65,
		'colRadChckLabelColorOver' : 0x5b5f65,
		'colRadChckLabelColorDown' : 0x5b5f65,
		'colKntrInputLabelColorUp' : 0x5b5f65,
		'colKntrInputLabelColorOver' : 0x5b5f65,
		'colKntrInputLabelColorDown' : 0x5b5f65,
		'colOtherInputColor' : 0x5b5f65
	},
	'qcrowpicker':{
		'rowBtnBckgrndColorDown' : 0x9fcc3b,
		'rowContainBorderColor' : 0xa6a8ab,
                'rowContainBckgrndColor' : 0xffffff,
                'rowBtnBckgrndColorUp' : 0xffffff,
                'rowBtnLabelColorUp' : 0x5b5f65,
                'rowBtnLabelColorDown' : 0x5b5f65,
                'zoomOverlayBckgrndColor' : 0x000000,
                'tooltipBorderColor' : 0xa6a8ab,
                'tooltipBckgrndColor' : 0xffffff,
                'tooltipFontColor' : 0x5b5f65,
                'zoomBorderColor' : 0xa6a8ab,
                'zoomBckgrndColor' : 0xffffff,
                'rowContainLabelColor' : 0x5b5f65,
                'rowBtnBorderColorUp' : 0xcccccc,
                'rowBtnBorderColorOver' : 0xa6a8ab,
                'rowBtnBorderColorDown' :  0x9fcc3b,
                'rowBtnBckgrndColorOver' : 0xffffff,
                'rowBtnLabelColorOver' : 0x5b5f65,
                'rowBtnLabelOverlayBckgrndColor' : 0xffffff, 
                'rowRadChckLabelColorUp' : 0x5b5f65,
                'rowRadChckLabelColorOver' : 0x5b5f65,
                'rowRadChckLabelColorDown' : 0x5b5f65,
                'rowKntrInputLabelColorUp' : 0x555555,
                'rowKntrInputLabelColorOver' : 0x000000,
                'rowKntrInputLabelColorDown' : 0x000000,
                'rowOtherInputColor' : 0x5b5f65,
                'zoomGalleryBorderColor' : 0xa6a8ab
	},
	'qcrowpickertext':{
		'rowBtnBckgrndColorDown' : 0x9fcc3b,
		'rowContainBorderColor' : 0xa6a8ab,
                'rowContainBckgrndColor' : 0xffffff,
                'rowBtnBckgrndColorUp' : 0xffffff,
                'rowBtnLabelColorUp' : 0x5b5f65,
                'rowBtnLabelColorDown' : 0x5b5f65,
                'zoomOverlayBckgrndColor' : 0x000000,
                'tooltipBorderColor' : 0xa6a8ab,
                'tooltipBckgrndColor' : 0xffffff,
                'tooltipFontColor' : 0x5b5f65,
                'zoomBorderColor' : 0xa6a8ab,
                'zoomBckgrndColor' : 0xffffff,
                'rowContainLabelColor' : 0x5b5f65,
                'rowBtnBorderColorUp' : 0xcccccc,
                'rowBtnBorderColorOver' : 0xa6a8ab,
                'rowBtnBorderColorDown' :  0x9fcc3b,
                'rowBtnBckgrndColorOver' : 0xffffff,
                'rowBtnLabelColorOver' : 0x5b5f65,
                'rowBtnLabelOverlayBckgrndColor' : 0xffffff, 
                'rowRadChckLabelColorUp' : 0x5b5f65,
                'rowRadChckLabelColorOver' : 0x5b5f65,
                'rowRadChckLabelColorDown' : 0x5b5f65,
                'rowKntrInputLabelColorUp' : 0x555555,
                'rowKntrInputLabelColorOver' : 0x000000,
                'rowKntrInputLabelColorDown' : 0x000000,
                'rowOtherInputColor' : 0x5b5f65,
                'zoomGalleryBorderColor' : 0xa6a8ab
	},
	'qclinkedslider':{
		'rowBtnBckgrndColorDown' : 0xffbd1a, // Orange???
		'rowContainBorderColor' : 0xa6a8ab,
		'rowContainBckgrndColor' : 0xffffff,
		'rowBtnBckgrndColorUp' : 0xf2f2f2,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'tooltipBorderColor' : 0xa6a8ab,
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xffffff,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xa6a8ab,
		'rowBtnBorderColorOver' : 0x5b5f65,
		'rowBtnBorderColorDown' : 0x5b5f65,
		'rowBtnBckgrndColorOver' : 0xa6a8ab,
		'rowBtnLabelColorOver' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'rowRadChckLabelColorUp' : 0x5b5f65,
		'rowRadChckLabelColorOver' : 0x5b5f65,
		'rowRadChckLabelColorDown' : 0x5b5f65,
		'rowKntrInputLabelColorUp' : 0x5b5f65,
		'rowKntrInputLabelColorOver' : 0x5b5f65,
		'rowKntrInputLabelColorDown' : 0x5b5f65,
		'rowOtherInputColor' : 0x5b5f65,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'rowSldrTrackBorderColor' : 0xf2f2f2,
		'rowSldrTrackColor' : 0xd2d3d5,
		'rowSldrLabelColor' : 0x5b5f65,
		'rowSldrTickColor' : 0xf2f2f2,
		'rowSldrTickLabColor' : 0x5b5f65,
		'rowSldrHndleBorderColorUp' : 0xf2f2f2,
		'rowSldrHndleColorUp' : 0xd2d3d5,
		'rowSldrHndleColorDown' : 0xffffff,
		'rowSldrHndleLabFontColor' : 0xffffff,
		'rowSldrHndleLabBckgrndColor' : 0xffffff
	},
	'rankinggrid': {
		'rowBtnBckgrndColorDown' : 0xffffff,
		'rowContainBorderColor' : 0xcccccc,
		'rowContainBckgrndColor' : 0xcccccc,
		'rowBtnBckgrndColorUp' : 0xffffff,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'colContainBorderColor' : 0xcccccc,
		'colContainBckgrndColor' : 0xffffff,
		'tooltipBorderColor' : 0xcccccc,
		'tooltipBckgrndColor' : 0xf8f8f8,
		'tooltipFontColor' : 0x000000,
		'zoomBorderColor' : 0xcccccc,
		'zoomBckgrndColor' : 0xf5f5f5,
		'rowContainLabelColor' : 0x333333,
		'rowBtnBorderColorUp' : 0xd2d3d5,
		'rowBtnBorderColorOver' : 0x9FCC3B,
		'rowBtnBorderColorDown' : 0xd2d3d5,
		'rowBtnBckgrndColorOver' : 0xffffff,
		'rowBtnLabelColorOver' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xeeeeee,
		'rowRadChckLabelColorUp' : 0x555555,
		'rowRadChckLabelColorOver' : 0x000000,
		'rowRadChckLabelColorDown' : 0x000000,
		'zoomGalleryBorderColor' : 0xcccccc,
		'colContainLabelColor' : 0x333333,
		'colDzoneBorderColorUp' : 0xa6a8ab,
		'colDzoneBorderColorOver' : 0xa6a8ab,
		'colDzoneBckgrndColorUp' : 0xf2f2f2,
		'colDzoneBckgrndColorOver' : 0xffffff,
		'colDzoneLabColorUp' : 0x555555,
		'colDzoneLabColorOver' : 0x000000,
		'colDzoneLabOverlayBckgrndColor' : 0xeeeeee
	},
	'slider': {
		'rowBtnBckgrndColorDown' : 0x9fcc3b,
	        'rowContainBorderColor' : 0xf2f2f2,
	        'rowContainBckgrndColor' : 0xf2f2f2,
	        'rowBtnBckgrndColorUp' : 0xf2f2f2,
	        'rowBtnLabelColorUp' : 0x5b5f65,
	        'rowBtnLabelColorDown' : 0x5b5f65,
	        'zoomOverlayBckgrndColor' : 0x000000,
	        'colContainBorderColor' : 0xa6a8ab,
	        'colContainBckgrndColor' : 0xffffff,
	        'tooltipBorderColor' : 0xa6a8ab,
	        'tooltipBckgrndColor' : 0xffffff,
	        'tooltipFontColor' : 0x5b5f65,
	        'zoomBorderColor' : 0xa6a8ab,
	        'zoomBckgrndColor' : 0xf2f2f2,
	        'colBtnBckgrndColorUp' : 0xf2f2f2,
	        'colBtnBckgrndColorOver' : 0xa6a8ab,
	        'colBtnBckgrndColorDown' : 0xffbd1a,
	        'colBtnLabelColorUp' : 0x5b5f65,
	        'colBtnLabelColorOver' : 0x5b5f65,
	        'colBtnLabelColorDown' : 0x5b5f65,
	        'colSldrTrackBorderColor' : 0xf2f2f2,
	        'colSldrTrackColor' : 0xd2d3d5,
	        'colSldrHighlightColor' : 0x9FCC3B,
	        'colSldrTickColor' : 0x9FCC3B,
	        'colSldrTickLabColor' : 0x5b5f65,
		'colSldrHndleColorUp' : 0xffffff,
		'colSldrHndleColorDown' : 0xffffff,
		'colSldrHndleLabFontColor' : 0x5b5f65,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorUp' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'colContainLabelColor' : 0x5b5f65,
		'colBtnBorderColorUp' : 0xa6a8ab,
		'colBtnBorderColorOver' : 0x5b5f65,
		'colBtnBorderColorDown' : 0x5b5f65,
		'colBtnLabelOverlayBckgrndColor' : 0xffffff,
		'colRadChckLabelColorUp' : 0x5b5f65,
		'colRadChckLabelColorOver' : 0x5b5f65,
		'colRadChckLabelColorDown' : 0x5b5f65,
		'colKntrInputLabelColorUp' : 0x5b5f65,
		'colKntrInputLabelColorOver' : 0x5b5f65,
		'colKntrInputLabelColorDown' : 0x5b5f65,
		'colOtherInputColor' : 0x5b5f65,
		'colSldrHndleBorderColorUp' : 0xd2d3d5,
		'colSldrHndleBorderColorDown' : 0x9ecc3b,
		'colSldrHndleLabBckgrndColor' : 0xffffff
	},
	'qcslidermatrix':{
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'rowBtnBorderColorUp' : 0xa6a8ab,
		'colContainBckgrndColor' : 0xffffff,
		'colBtnBckgrndColorUp' : 0xf2f2f2,
		'colBtnBckgrndColorDown' : 0xffbd1a,
		'colBtnBorderColorUp' : 0xa6a8ab,
		'colSldrTrackBorderColor' : 0xf2f2f2,
		'colSldrTrackColor' : 0xd2d3d5,
		'colSldrHighlightColor' : 0x9fcc3b,
		'colSldrTickColor' : 0x9fcc3b,
		'colSldrTickLabColor' : 0x5b5f65,
		'colSldrHndleLabFontColor' : 0x5b5f65,
		'colSldrHndleLabBckgrndColor' : 0xffffff,
		'rowBtnBckgrndColorDown' : 0x9fcc3b,
		'rowContainBorderColor' : 0xf2f2f2,
		'rowContainBckgrndColor' : 0xf2f2f2,
		'rowBtnBckgrndColorUp' : 0xf2f2f2,
		'colContainBorderColor' : 0xa6a8ab,
		'tooltipBorderColor' : 0xa6a8ab,
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xf2f2f2,
		'colBtnBckgrndColorOver' : 0xa6a8ab,
		'colBtnLabelColorUp' : 0x5b5f65,
		'colBtnLabelColorOver' : 0x5b5f65,
		'colBtnLabelColorDown' : 0x5b5f65,
		'colSldrHndleColorUp' : 0xffffff,
		'colSldrHndleColorDown' : 0xffffff,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnBorderColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab,
		'colContainLabelColor' : 0x5b5f65,
		'colBtnBorderColorOver' : 0x5b5f65,
		'colBtnBorderColorDown' : 0x5b5f65,
		'colBtnLabelOverlayBckgrndColor' : 0xffffff,
		'colRadChckLabelColorUp' : 0x5b5f65,
		'colRadChckLabelColorOver' : 0x5b5f65,
		'colRadChckLabelColorDown' : 0x5b5f65,
		'colKntrInputLabelColorUp' : 0x5b5f65,
		'colKntrInputLabelColorOver' : 0x5b5f65,
		'colKntrInputLabelColorDown' : 0x5b5f65,
		'colOtherInputColor' : 0x5b5f65,
		'colSldrHndleBorderColorUp' : 0xd2d3d5,
		'colSldrHndleBorderColorDown' : 0x9ecc3b
	},
	'clickandfly':{
		'zoomOverlayBckgrndColor' : 0x000000,
		'rowBtnBckgrndColorUp' : 0xffffff,
		'rowBtnBckgrndColorOver' : 0xffffff,
		'rowBtnBckgrndColorDown' : 0xffffff,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorOver' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'rowBtnBorderColorUp' : 0xd2d3d5,
		'rowBtnBorderColorOver' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x9fcc3b,
		'rowContainBorderColor' : 0xa6a8ab,
		'rowContainBckgrndColor' : 0xffffff,
		'rowContainLabelColor' : 0x5b5f65,
		'rowRadChckLabelColorUp' : 0x5b5f65,
		'rowRadChckLabelColorOver' : 0x5b5f65,
		'rowRadChckLabelColorDown' : 0x5b5f65,
		'rowKntrInputLabelColorUp' : 0x555555,
		'rowKntrInputLabelColorOver' : 0x000000,
		'rowKntrInputLabelColorDown' : 0x000000,
		'rowOtherInputColor' : 0x5b5f65,
		'bucketBorderColor' : 0xd2d3d5,
		'bucketPrimBckgrndColor' : 0xf2f2f2,
		'bucketSecBckgrndColor' : 0xf2f2f2,
		'tooltipBorderColor' : 0xa6a8ab, 
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab
	},
	'qcclickandfly':{
		'rowBtnBckgrndColorDown' : 0xffffff,
                'rowBtnBckgrndColorUp' : 0xffffff,
                'rowBtnLabelColorUp' : 0x5b5f65,
                'rowBtnLabelColorDown' : 0x5b5f65,
                'zoomOverlayBckgrndColor' : 0x000000,
                'rowBtnBorderColorUp' : 0xd2d3d5,
                'rowBtnBorderColorOver' : 0xa6a8ab,
                'rowBtnBorderColorDown' : 0x9fcc3b,
                'rowBtnBckgrndColorOver' : 0xffffff,
                'rowBtnLabelColorOver' : 0x5b5f65,
                'rowKntrInputLabelColorUp' : 0x555555,
                'rowKntrInputLabelColorOver' : 0x000000,
                'rowKntrInputLabelColorDown' : 0x000000,
                'bucketPrimBckgrndColor' : 0xf2f2f2,
                'bucketSecBckgrndColor' : 0xf2f2f2,
                'bucketBorderColor' : 0xd2d3d5,
                'rowContainBorderColor' : 0xa6a8ab,
                'rowContainBckgrndColor' : 0xffffff,
                'tooltipBorderColor' : 0xa6a8ab,
                'tooltipBckgrndColor' : 0xffffff,
                'tooltipFontColor' : 0x5b5f65,
                'zoomBorderColor' : 0xa6a8ab,
                'zoomBckgrndColor' : 0xffffff,
                'rowContainLabelColor' : 0x5b5f65,
                'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
                'rowRadChckLabelColorUp' : 0x5b5f65,
                'rowRadChckLabelColorOver' : 0x5b5f65,
                'rowRadChckLabelColorDown' : 0x5b5f65,
                'rowOtherInputColor' : 0x5b5f65,
                'zoomGalleryBorderColor' : 0xa6a8ab
	},
	'qcdragndrop':{
		'rowContainBorderColor' : 0xcccccc,
		'rowContainBckgrndColor' : 0xcccccc,
		'rowContainLabelColor' : 0x333333,
		'rowBtnBorderColorUp' : 0xd2d3d5,
		'rowBtnBorderColorOver' : 0x9fcc3b,
		'rowBtnBorderColorDown' : 0xd2d3d5,
		'rowBtnBckgrndColorUp' : 0xffffff,
		'rowBtnBckgrndColorOver' : 0xffffff,
		'rowBtnBckgrndColorDown' : 0xffffff,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorOver' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xeeeeee,
		'rowRadChckLabelColorUp' : 0x555555,
		'rowRadChckLabelColorOver' : 0x000000,
		'rowRadChckLabelColorDown' : 0x000000,
		'colContainBckgrndColor' : 0xffffff,
		'colContainLabelColor' : 0x333333,
		'colDzoneBorderColorUp' : 0xa6a8ab,
		'colDzoneBorderColorOver' : 0xa6a8ab,
		'colDzoneBckgrndColorUp' : 0xf2f2f2,
		'colDzoneBckgrndColorOver' : 0xffffff,
		'colDzoneLabOverlayBckgrndColor' : 0xeeeeee,
		'tooltipFontColor' : 0x000000,
		'tooltipBorderColor' : 0xcccccc,
		'tooltipBckgrndColor' : 0xf8f8f8,
		'zoomOverlayBckgrndColor' : 0x000000,
		'zoomGalleryBorderColor' : 0xcccccc,
		'zoomBorderColor' : 0xcccccc,
		'zoomBckgrndColor' : 0xf5f5f5,
		'colContainBorderColor' : 0xcccccc,
		'colDzoneLabColorUp' : 0x555555,
		'colDzoneLabColorOver' : 0x000000
	},
	'qcdragnflag':{
		'rowBtnBckgrndColorDown' : 0xffffff,
		'rowBtnBckgrndColorUp' : 0xffffff,
		'rowBtnLabelColorUp' : 0x5b5f65,
		'rowBtnLabelColorDown' : 0x5b5f65,
		'zoomOverlayBckgrndColor' : 0x000000,
		'rowBtnBorderColorUp' : 0xd2d3d5,
		'rowBtnBorderColorOver' : 0xa6a8ab,
		'rowBtnBorderColorDown' : 0x9fcc3b,
		'rowBtnBckgrndColorOver' : 0xffffff,
		'rowBtnLabelColorOver' : 0x5b5f65,
		'colSldrTrackBorderColor' : 0xf2f2f2,
		'colSldrTrackColor' : 0xd2d3d5,
		'rowBtnFlagStickCircColor' : 0x5b5f65,
		'rowBtnValLabColor' : 0x5b5f65,
		'rowContainBorderColor' : 0xa6a8ab,
		'rowContainBckgrndColor' : 0xf2f2f2,
		'tooltipBorderColor' : 0xa6a8ab,
		'tooltipBckgrndColor' : 0xffffff,
		'tooltipFontColor' : 0x5b5f65,
		'zoomBorderColor' : 0xa6a8ab,
		'zoomBckgrndColor' : 0xffffff,
		'colSldrTickColor' : 0x9fcc3b,
		'colSldrTickLabColor' : 0x5b5f65,
		'rowContainLabelColor' : 0x5b5f65,
		'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
		'zoomGalleryBorderColor' : 0xa6a8ab
	},
	'virtualhighlighter':{
		'drawColor' : "#FFFF00",
		'gridColor' : "#000000",
		'clearNoopinionBGColor' : "#9FCC3B",
		'clearNoopinionTextColor' : "#FFFFFF"
	},
	'clickspot':{
		'SpotFillColor' : "#9FCC3B",
		'SpotStrokeColor' : "#000000",
		'undoResetBGColor' : "#9FCC3B",
		'undoResetTextColor' : "#FFFFFF"
	},
	'clickbasedhighlighter':{
		'likeSliceColor' : "#00FF00",
		'unlikeSliceColor' : "#FF0000",
		'clearNoopinionBGColor' : "#9FCC3B",
		'clearNoopinionTextColor' : "#FFFFFF"
	},
	'videoplayer':{
		'playBtnBGColor' : "#FF00FF",
		'color' : "#FFFFFF",
		'backgroundColor' : "#FF00FF"
	},
	'autosum':{
		'rowsumcolor' : "#9FCC3B",
		'columnsumcolor' : "#9FCC3B",
		'grandtotalcolor' : "#9FCC3B",
		'autosumtextcolor': "#FFFFFF"
	},
	'mediaupload':{
		'snapbuttonlabelcolor': "#fff",
		 'inputfilenamecolor': "#000",
		 'inputfilelabelcolor': "#fff",
		 'uploadbuttonbackgrouncolor': "#9FCC3B",
		 'inputfilebackgrouncolor': "#9FCC3B",
		 'uploadbuttonlabelcolor': "#fff",
		 'snapbuttonbackgrouncolor': "#9FCC3B"
		
	}
})


