/**
 * qcbtnmatrix class
 * Inherits from SESurveyTool
 */
function qcbtnmatrix(questionContainers, json, globalOpts) {
    SESurveyTool.prototype.init.call(this, questionContainers, json, globalOpts);
}
qcbtnmatrix.prototype = Object.create(SESurveyTool.prototype);
qcbtnmatrix.prototype.type = function(){
    return "qcbtnmatrix";
}
qcbtnmatrix.prototype.getDependencies = function(){
    return [
        {'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcomponent/BtnMatrix/BtnMatrix.js'}
        //{'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcore/QFactory.js'},
		//{'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcore/QContainer.js'},
		//{'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcore/QWidget.js'} 
    ];
}
qcbtnmatrix.prototype.setInitialResponses = function (){
    var dimResp = [];
    $.each(this.subquestions, function(rowid, e) {
        var colResp = [];
        $.each(e.inputs.filter(":checked"), function(i, e) {
            colResp.push({index:$(e).attr("colid")});
        });
        dimResp.push({rowIndex: rowid, colIndex:colResp});
    });
    this.component.setDimenResp(dimResp);
}
qcbtnmatrix.prototype.setResponses = function (){
    console.log("Set responses");
    var response = this.getResponse();
    if (response == null) return;
    console.log("Set responses2");
    this.clearInputs(); // need to clear the responses before setting them.
    var that = this;

    $.each($(response.Value), function(i,e) { // Sets categories
        var resp = e.split('^');
		if(typeof surveyPlatform=="undefined"){      // This code belongs to Dimensions
			var inputs = that.subquestions[resp[0]].inputs;
			var multi = inputs.filter('input[type=checkbox]');
			if (multi) inputs.filter('[value='+resp[1]+']').val($.makeArray(resp[1]));
			else inputs.val($.makeArray(resp[1]));
		}else if(surveyPlatform=="Nfield"){     // This code belongs to Nfield
			var resp1=resp[0].split('-');
			var inputs = that.subquestions[resp1[1]].inputs;
			var temp = resp[1].split('-');
			var multi = inputs.filter('input[type=checkbox]');
			if (multi) inputs.filter('[value='+resp1[0]+'-'+temp[1]+']').val($.makeArray(resp1[0]+'-'+temp[1]));
			else inputs.val($.makeArray(resp1[0]+'-'+temp[1]));
		}
    });

}
qcbtnmatrix.prototype.build = function(){
        this.component = new BtnMatrix();
		 var finalparams=this.params();
		var rowArray = [],
            colArray = [],
            that = this;

        // Create questions and columns to build
        this.buildArraysFromGrid();

        // Build up row array
        $.each(this.subquestions, function (i, e) {
            var label = e.label;
            label.find('span').removeClass('mrQuestionText');
			label.find("span").removeClass('mrSingleText');
            label.find("span").removeClass('mrMultipleText');
			if(typeof surveyPlatform=="undefined"){      // This code belongs to Dimensions
				var qid = e.id;
			}else if(surveyPlatform=="Nfield"){     // This code belongs to Nfield
				var subqid=e.inputs.filter('input[type!=text]').eq(0).attr("value");
				subqid=subqid.split("-");
				var qid = subqid[0]+'-'+e.id;
			}
            rowArray.push({
                id: qid,
                label: label.html(),
                description: label.text(),
                image: e.image
            });
        });

        // Build up column array
        $.each(this.columnheaders, function (i, e) {
            var label = $(e.label);
            label.find('span').removeClass('mrQuestionText');
			label.find("span").removeClass('mrSingleText');
            label.find("span").removeClass('mrMultipleText');
            label.find("span").attr('style','');

            var image = label.find('img');
            image.hide();
			if(typeof surveyPlatform=="undefined"){      // This code belongs to Dimensions
				var colLabel = label.html();
				var colDescription = label.text();
				var colIsRadio = $(that.subquestions[0].inputs[i]).attr('isexclusive') == "true";
			}else if(surveyPlatform=="Nfield"){     // This code belongs to Nfield
				var colLabel = label.html().split("|")[0];
				var colDescription = label.text().split("|")[0];
				var colIsRadio = (typeof label.text().split("|")[1]!="undefined" && label.text().split("|")[1].toLowerCase().trim()=="exclusive")?true:false
			}
			colArray.push({
                id: $(that.subquestions[0].inputs[i]).val(),
                label: colLabel,
                description: colDescription,
                image: image.attr('src'),
                isRadio: colIsRadio
            });
			if(typeof surveyPlatform=="undefined"){      // This code belongs to Dimensions
				if (colArray[colArray.length-1].isRadio) {
					colArray[colArray.length-1].type = 'radiocheck';  // radio button
				}
			}else if(surveyPlatform=="Nfield"){     // This code belongs to Nfield
				if(typeof label.text().split("|")[1]!="undefined" && label.text().split("|")[1].toLowerCase().trim()=="exclusive"){
					colArray[colArray.length-1].type = 'radiocheck';  // radio button
				}
			}
        });

        
        this.component.rowArray(rowArray);
        this.component.columnArray(colArray);
        this.component.baseTool="btnmatrix";
        this.component.params(finalparams);
        this.deferred.resolve();
		var mrErrorTextLength = $('.mrErrorText').parent().parent('.qwidget_label_container').length;

		for(i=0; i < mrErrorTextLength; i++){
			$ele = $( ".qwidget_label_container .mrErrorText:eq( "+i+" )" ).html();
	
			$( ".qwidget_label_container .mrErrorText:eq( "+i+" )" ).parent().parent().parent().prepend('<span class="mrErrorText" style="">'+$ele+'</span>');
		}
			$( ".qwidget_label_container .mrErrorText" ).remove();
}
qcbtnmatrix.prototype.toolOptions = function() {
        $.extend(this.options, eval("this.options."+qcbtnmatrix.prototype.type()));
		switch(pageLayout.deviceType.toUpperCase()) {
            case "LARGETABLET":
            case "MEDIUMTABLET":
            case "SMALLTABLET":
            case "SMARTPHONETOUCH":
			    if(this.orientation==0||this.orientation==180) 
                return  {
                    'rowBtnUseZoom' : false,
//                    'rowBtnBckgrndColorDown' : 0xfce6c9,
                    'rowContainLabel' : "Row Container Label",
                    'rowBtnShowLabel' : true,
                    'rowBtnUseTooltip' : true,
                    'rowContainWidth' : 315,
                    'compQuestionType' : "Single Choice",
                    'rowContainType' : "horizontal grid layout",
                    'rowContainPadding' : 0,
                    'rowContainHgap' : 0,
                    'rowContainVgap' : 30,
                    'rowContainHoffset' : 0,
                    'rowContainVoffset' : 20,
                    'rowContainBorderStyle' : "none",
                    'rowContainBorderWidth' : 1,
//                    'rowContainBorderColor' : 0xff00ff,
//                    'rowContainBckgrndColor' : 0xf5f5f5,
                    'rowBtnDefaultType' : "Base",
                    'rowBtnWidth' : 280,
                    'rowBtnHeight' : 54,
                    'rowBtnBorderStyle' : "none",
                    'rowBtnBorderRadius' : 0,
                    'rowBtnShowBckgrnd' : false,
//                    'rowBtnBckgrndColorUp' : 0xffffff,
                    'rowBtnLabelPlacement' : "center overlay",
                    'rowBtnLabelHalign' : "left",
                    'rowBtnLabelFontSize' : 26,
                    'rowBtnLabelHoffset' : 10,
                    'rowBtnLabelVoffset' : 0,
//                    'rowBtnLabelColorUp' : 0x5b5f65,
//                    'rowBtnLabelColorDown' : 0x5b5f65,
                    'rowBtnImgHoffset' : 0,
                    'rowBtnImgVoffset' : 0,
                    'rowShowStamp' : false,
                    'rowStampImp' : "",
                    'rowStampWidth' : 30,
                    'rowStampHeight' : 21,
                    'rowStampHoffset' : 0,
                    'rowStampVoffset' : 0,
                    'rowKantBtnLabelWidth' : 100,
                    'rowZoomHoffset' : 0,
                    'rowZoomVoffset' : 0,
//                    'zoomOverlayBckgrndColor' : 0x000000,
                    'zoomOverlayAlpha' : 88,
                    'zoomGalleryPadding' : 10,
                    'zoomGalleryHoffset' : 0,
                    'zoomGalleryVoffset' : 0,
                    'zoomCloseImp' : "",
                    'zoomCloseWidth' : 22,
                    'zoomCloseHeight' : 22,
                    'zoomCloseHoffset' : 0,
                    'zoomCloseVoffset' : 0,
                    'compCapValue' : 0,
                    'rowContainHeight' : 840,
                    'tooltipWidth' : 100,
                    'tooltipBorderWidth' : 1,
//                    'tooltipBorderColor' : 0xcccccc,
//                    'tooltipBckgrndColor' : 0xf5f5f5,
                    'tooltipLabelHalign' : "left",
                    'tooltipFontSize' : 12,
//                    'tooltipFontColor' : 0x555555,
                    'zoomImp' : "",
                    'zoomWidth' : 20,
                    'zoomHeight' : 20,
                    'zoomBorderWidth' : 1,
//                    'zoomBorderColor' : 0xcccccc,
//                    'zoomBckgrndColor' : 0xf5f5f5,
                    'compContainPos' : "relative",
                    'compRTL' : false,
                    'rowContainAutoWidth' : true,
                    'rowContainAutoHeight' : true,
                    'rowContainBckgrndDispType' : "none",
                    'rowContainImgImport' : "",
                    'rowContainImgImportHoffset' : 0,
                    'rowContainImgImportVoffset' : 0,
                    'rowContainShowLabel' : false,
                    'rowContainLabelHalign' : "left",
                    'rowContainLabelFontSize' : 18,
                    'rowContainLabelPadding' : 0,
//                    'rowContainLabelColor' : 0x555555,
                    'rowBtnPadding' : 5,
                    'rowBtnBorderWidthUp' : 1,
                    'rowBtnBorderWidthDown' : 1,
//                    'rowBtnBorderColorUp' : 0xcccccc,
//                    'rowBtnBorderColorDown' : 0xcccccc,
                    'rowBtnLabelOvrWidth' : false,
                    'rowBtnLabelWidth' : 150,
                    'rowBtnLabelOverlayShowBckgrnd' : false,
//                    'rowBtnLabelOverlayBckgrndColor' : 0xeeeeee,
                    'rowBtnLabelOverlayPadding' : 0,
                    'rowTxtBtnAdjustHeightType' : "none",
                    'zoomActionType' : "click append image",
                    'zoomGalleryBorderStyle' : "solid",
                    'zoomGalleryBorderWidth' : 1,
//                    'zoomGalleryBorderColor' : 0xcccccc,
                    'colContainLabel' : "Column Container Label",
                    'rowBckgrndShowImp' : false,
                    'rowBckgrndImpUp' : "",
                    'rowBckgrndImpDown' : "",
                    'colContainType' : "horizontal grid layout",
                    'colContainWidth' : 575,
                    'colContainHgap' : 2,
                    'colContainVgap' : 0,
                    'colContainHoffset' : -30,
                    'colContainVoffset' : -20,
                    'colContainBorderStyle' : "none",
                    'colContainBorderWidth' : 0,
//                    'colContainBorderColor' : 0xeeeeee,
//                    'colContainBckgrndColor' : 0xf5f5f5,
                    'colZoomHoffset' : 0,
                    'colZoomVoffset' : 0,
                    'rowContainSetRowPer' : 3,
                    'rowContainScrlEndPos' : 50,
                    'rowContainChldInitAlpha' : 100,
                    'rowContainChldEndAlpha' : 100,
                    'rowContainAutoNext' : true,
                    'colBtnDefaultType' : "Base",
                    'colBtnWidth' : 64,
                    'colBtnHeight' : 64,
                    'colBtnBorderStyle' : "solid",
                    'colBtnBorderRadius' : 0,
                    'colBtnShowBckgrnd' : true,
                    'colRadShowImp' : false,
                    'colChkShowImp' : true,
//                    'colBtnBckgrndColorUp' : 0xf5f5f5,
//                    'colBtnBckgrndColorOver' : 0xcccccc,
//                    'colBtnBckgrndColorDown' : 0xfce6c9,
                    'colRadImpUp' : "",
                    'colRadImpOver' : "",
                    'colRadImpDown' : "",
                    'colBtnShowLabel' : false,
                    'colBtnLabelPlacement' : "bottom",
                    'colBtnLabelHalign' : "left",
                    'colBtnLabelFontSize' : 15,
                    'colBtnLabelHoffset' : 0,
                    'colBtnLabelVoffset' : 0,
//                    'colBtnLabelColorUp' : 0x555555,
//                    'colBtnLabelColorOver' : 0x000000,
//                    'colBtnLabelColorDown' : 0x555555,
                    'colBtnImgHoffset' : 0,
                    'colBtnImgVoffset' : 0,
                    'colShowStamp' : false,
                    'colStampImp' : "",
                    'colStampWidth' : 15,
                    'colStampHeight' : 15,
                    'colStampHoffset' : 0,
                    'colStampVoffset' : 0,
                    'colKantBtnLabelWidth' : 100,
                    'colRadChckLabelWidth' : 100,
                    'colOtherInitTxt' : "Please specify...",
                    'colOtherMinVal' : 1,
                    'colOtherMaxVal' : 100,
                    'colOtherMsgWidth' : 100,
                    'colBtnMouseOverDownShadow' : false,
                    'colBtnMouseOverBounce' : false,
                    'colBtnMouseOverScale' : 100,
                    'colBtnMouseDownScale' : 100,
                    'colBtnMouseDownAlpha' : 100,
                    'colBtnUseTooltip' : true,
                    'colBtnUseZoom' : false,
                    'compClickType' : "rating",
                    'colBtnPadding' : 0,
                    'colBtnBorderWidthUp' : 0,
                    'colBtnBorderWidthOver' : 0,
                    'colBtnBorderWidthDown' : 0,
                    'colContainHeight' : 840,
                    'colContainPadding' : 0,
                    'colContainBckgrndDispType' : "none",
                    'colContainImgImport' : "",
                    'colContainImgImportHoffset' : 0,
                    'colContainImgImportVoffset' : 0,
                    'colContainShowLabel' : false,
                    'colContainLabelHalign' : "left",
                    'colContainLabelFontSize' : 18,
                    'colContainLabelPadding' : 5,
//                    'colContainLabelColor' : 0x333333,
                    'rowContainScrlAnimSpeed' : 800,
                    'rowContainChldEnableAlpha' : 50,
                    'rowContainGoOpaque' : true,
                    'colContainShowTopLabelHeader' : false,
//                    'colBtnBorderColorUp' : 0xcccccc,
//                    'colBtnBorderColorOver' : 0xff0000,
//                    'colBtnBorderColorDown' : 0xcccccc,
                    'colBtnLabelOvrWidth' : false,
                    'colBtnLabelWidth' : 125,
                    'colBtnLabelOverlayShowBckgrnd' : true,
//                    'colBtnLabelOverlayBckgrndColor' : 0xeeeeee,
                    'colBtnLabelOverlayPadding' : 2,
                    'colTxtBtnAdjustHeightType' : "none",
                    'colRadChckLabelHalign' : "left",
                    'colRadChckLabelFontSize' : 18,
//                    'colRadChckLabelColorUp' : 0x555555,
//                    'colRadChckLabelColorOver' : 0x000000,
//                    'colRadChckLabelColorDown' : 0x000000,
                    'colRadChckLabelHoffset' : 0,
                    'colRadChckLabelVoffset' : 15,
                    'colKntrInputTxtAreaWidth' : 125,
                    'colKntrInputLabelHalign' : "left",
                    'colKntrInputLabelWidth' : 200,
                    'colKntrInputLabelHoffset' : 0,
                    'colKntrInputLabelVoffset' : 10,
                    'colKntrInputLabelFontSize' : 18,
//                    'colKntrInputLabelColorUp' : 0x555555,
//                    'colKntrInputLabelColorOver' : 0x000000,
//                    'colKntrInputLabelColorDown' : 0x000000,
                    'colOtherInputHalign' : "left",
                    'colOtherInputFontSize' : 15,
//                    'colOtherInputColor' : 0x555555,
                    'colContainOptValign' : "middle"
				}
			else
                return {
//                    'rowBtnBckgrndColorDown' : 0xffbd1a,
                    'rowBtnShowLabel' : true,
                    'rowBtnUseTooltip' : false,
                    'rowContainWidth' : 870,
                    'compQuestionType' : "Single Choice",
                    'rowContainType' : "horizontal grid layout",
                    'rowContainPadding' : 0,
                    'rowContainHgap' : 5,
                    'rowContainVgap' : 5,
                    'rowContainHoffset' : 0,
                    'rowContainVoffset' : 0,
                    'rowContainBorderStyle' : "none",
                    'rowContainBorderWidth' : 0,
//                    'rowContainBorderColor' : 0xa6a8ab,
//                    'rowContainBckgrndColor' : 0xffffff,
                    'rowBtnDefaultType' : "Base",
                    'rowBtnWidth' : 200,
                    'rowBtnHeight' : 44,
                    'rowBtnBorderStyle' : "solid",
                    'rowBtnBorderRadius' : 0,
                    'rowBtnShowBckgrnd' : false,
//                    'rowBtnBckgrndColorUp' : 0xf2f2f2,
                    'rowBtnLabelPlacement' : "center overlay",
                    'rowBtnLabelHalign' : "left",
                    'rowBtnLabelFontSize' : 20,
                    'rowBtnLabelHoffset' : 0,
                    'rowBtnLabelVoffset' : 20,
//                    'rowBtnLabelColorUp' : 0x5b5f65,
//                    'rowBtnLabelColorDown' : 0x5b5f65,
                    'rowBtnImgHoffset' : 0,
                    'rowBtnImgVoffset' : 20,
                    'rowShowStamp' : false,
                    'rowStampImp' : "",
                    'rowStampWidth' : 30,
                    'rowStampHeight' : 30,
                    'rowStampHoffset' : 0,
                    'rowStampVoffset' : 0,
                    'rowKantBtnLabelWidth' : 125,
                    'rowZoomHoffset' : 0,
                    'rowZoomVoffset' : 0,
//                    'zoomOverlayBckgrndColor' : 0x000000,
                    'zoomOverlayAlpha' : 80,
                    'zoomGalleryPadding' : 10,
                    'zoomGalleryHoffset' : 0,
                    'zoomGalleryVoffset' : 0,
                    'zoomCloseImp' : "",
                    'zoomCloseWidth' : 22,
                    'zoomCloseHeight' : 22,
                    'zoomCloseHoffset' : 0,
                    'zoomCloseVoffset' : 0,
                    'compCapValue' : 0,
                    'rowContainHeight' : 600,
                    'rowBckgrndShowImp' : false,
                    'rowBckgrndImpUp' : "",
                    'rowBckgrndImpDown' : "",
                    'colContainType' : "horizontal grid layout",
                    'colContainWidth' : 870,
                    'colContainHgap' : 15,
                    'colContainVgap' : 0,
                    'colContainHoffset' : 0,
                    'colContainVoffset' : 20,
                    'colContainBorderStyle' : "none",
                    'colContainBorderWidth' : 0,
//                    'colContainBorderColor' : 0xa6a8ab,
//                    'colContainBckgrndColor' : 0xffffff,
                    'tooltipWidth' : 150,
                    'tooltipBorderWidth' : 2,
//                    'tooltipBorderColor' : 0xa6a8ab,
//                    'tooltipBckgrndColor' : 0xffffff,
                    'tooltipLabelHalign' : "left",
                    'tooltipFontSize' : 18,
//                    'tooltipFontColor' : 0x5b5f65,
                    'zoomImp' : "",
                    'zoomWidth' : 20,
                    'zoomHeight' : 20,
                    'colZoomHoffset' : 0,
                    'colZoomVoffset' : 0,
                    'zoomBorderWidth' : 1,
//                    'zoomBorderColor' : 0xa6a8ab,
//                    'zoomBckgrndColor' : 0xffffff,
                    'rowContainSetRowPer' : 3,
                    'rowContainScrlEndPos' : 150,
                    'rowContainChldInitAlpha' : 100,
                    'rowContainChldEndAlpha' : 0,
                    'rowContainAutoNext' : true,
                    'colBtnDefaultType' : "Base",
                    'colBtnWidth' : 44,
                    'colBtnHeight' : 44,
                    'colBtnBorderStyle' : "none",
                    'colBtnBorderRadius' : 2,
                    'colBtnShowBckgrnd' : true,
                    'colRadShowImp' : true,
                    'colChkShowImp' : true,
//                    'colBtnBckgrndColorUp' : 0xffffff,
//                    'colBtnBckgrndColorOver' : 0xf2f2f2,
//                    'colBtnBckgrndColorDown' : 0xffbd1a,
                    'colBtnShowLabel' : false,
                    'colBtnLabelPlacement' : "bottom",
                    'colBtnLabelHalign' : "center",
                    'colBtnLabelFontSize' : 14,
                    'colBtnLabelHoffset' : 0,
                    'colBtnLabelVoffset' : 0,
//                    'colBtnLabelColorUp' : 0x5b5f65,
//                    'colBtnLabelColorOver' : 0x5b5f65,
//                    'colBtnLabelColorDown' : 0x5b5f65,
                    'colBtnImgHoffset' : 0,
                    'colBtnImgVoffset' : 0,
                    'colShowStamp' : false,
                    'colStampImp' : "",
                    'colStampWidth' : 30,
                    'colStampHeight' : 30,
                    'colStampHoffset' : 0,
                    'colStampVoffset' : 0,
                    'colKantBtnLabelWidth' : 100,
                    'colRadChckLabelWidth' : 150,
                    'colOtherInitTxt' : "",
                    'colOtherMinVal' : 1,
                    'colOtherMaxVal' : 100,
                    'colOtherMsgWidth' : 100,
                    'colBtnMouseOverDownShadow' : false,
                    'colBtnMouseOverBounce' : false,
                    'colBtnMouseOverScale' : 100,
                    'colBtnMouseDownScale' : 100,
                    'colBtnMouseDownAlpha' : 100,
                    'colBtnUseTooltip' : false,
                    'colBtnUseZoom' : false,
                    'compClickType' : "rating",
                    'colBtnPadding' : 5,
                    'colBtnBorderWidthUp' : 2,
                    'colBtnBorderWidthOver' : 2,
                    'colBtnBorderWidthDown' : 4,
                    'compContainPos' : "relative",
                    'compRTL' : false,
                    'rowContainAutoWidth' : true,
                    'rowContainAutoHeight' : true,
                    'rowContainBckgrndDispType' : "none",
                    'rowContainImgImport' : "",
                    'rowContainImgImportHoffset' : 0,
                    'rowContainImgImportVoffset' : 0,
                    'rowContainShowLabel' : false,
                    'rowContainLabelHalign' : "left",
                    'rowContainLabelFontSize' : 18,
                    'rowContainLabelPadding' : 4,
//                    'rowContainLabelColor' : 0x5b5f65,
                    'rowBtnPadding' : 10,
                    'rowBtnBorderWidthUp' : 2,
                    'rowBtnBorderWidthDown' : 2,
//                    'rowBtnBorderColorUp' : 0xa6a8ab,
//                    'rowBtnBorderColorDown' : 0x5b5f65,
                    'rowBtnLabelOvrWidth' : false,
                    'rowBtnLabelWidth' : 100,
                    'rowBtnLabelOverlayShowBckgrnd' : false,
//                    'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
                    'rowBtnLabelOverlayPadding' : 4,
                    'rowTxtBtnAdjustHeightType' : "none",
                    'zoomActionType' : "click append image",
                    'zoomGalleryBorderStyle' : "none",
                    'zoomGalleryBorderWidth' : 0,
//                    'zoomGalleryBorderColor' : 0xa6a8ab,
                    'colContainHeight' : 400,
                    'colContainPadding' : 0,
                    'colContainBckgrndDispType' : "none",
                    'colContainImgImport' : "",
                    'colContainImgImportHoffset' : 0,
                    'colContainImgImportVoffset' : 0,
                    'colContainShowLabel' : false,
                    'colContainLabelHalign' : "left",
                    'colContainLabelFontSize' : 18,
                    'colContainLabelPadding' : 4,
//                    'colContainLabelColor' : 0x5b5f65,
                    'rowContainScrlAnimSpeed' : 500,
                    'rowContainChldEnableAlpha' : 50,
                    'rowContainGoOpaque' : false,
                    'colContainShowTopLabelHeader' : false,
//                    'colBtnBorderColorUp' : 0xd2d3d5,
//                    'colBtnBorderColorOver' : 0xa6a8ab,
//                    'colBtnBorderColorDown' : 0xffbd1a,
                    'colBtnLabelOvrWidth' : false,
                    'colBtnLabelWidth' : 125,
                    'colBtnLabelOverlayShowBckgrnd' : false,
//                    'colBtnLabelOverlayBckgrndColor' : 0xffffff,
                    'colBtnLabelOverlayPadding' : 4,
                    'colTxtBtnAdjustHeightType' : "none",
                    'colRadChckLabelHalign' : "left",
                    'colRadChckLabelFontSize' : 18,
//                    'colRadChckLabelColorUp' : 0x5b5f65,
//                    'colRadChckLabelColorOver' : 0x5b5f65,
//                    'colRadChckLabelColorDown' : 0x5b5f65,
                    'colRadChckLabelHoffset' : 0,
                    'colRadChckLabelVoffset' : 2,
                    'colKntrInputTxtAreaWidth' : 125,
                    'colKntrInputLabelHalign' : "left",
                    'colKntrInputLabelWidth' : 150,
                    'colKntrInputLabelHoffset' : 0,
                    'colKntrInputLabelVoffset' : 5,
                    'colKntrInputLabelFontSize' : 18,
//                    'colKntrInputLabelColorUp' : 0x5b5f65,
//                    'colKntrInputLabelColorOver' : 0x5b5f65,
//                    'colKntrInputLabelColorDown' : 0x5b5f65,
                    'colOtherInputHalign' : "left",
                    'colOtherInputFontSize' : 16,
//                    'colOtherInputColor' : 0x5b5f65,
                    'colContainOptValign' : "middle"
                }			
            case "PC":
            case "OTHERDEVICE":
            default:
                return {
//                    'rowBtnBckgrndColorDown' : 0xffbd1a,
                    'rowBtnShowLabel' : true,
                    'rowBtnUseTooltip' : false,
                    'rowContainWidth' : 870,
                    'compQuestionType' : "Single Choice",
                    'rowContainType' : "horizontal grid layout",
                    'rowContainPadding' : 0,
                    'rowContainHgap' : 5,
                    'rowContainVgap' : 5,
                    'rowContainHoffset' : 0,
                    'rowContainVoffset' : 0,
                    'rowContainBorderStyle' : "none",
                    'rowContainBorderWidth' : 0,
//                    'rowContainBorderColor' : 0xa6a8ab,
//                    'rowContainBckgrndColor' : 0xffffff,
                    'rowBtnDefaultType' : "Base",
                    'rowBtnWidth' : 170,
                    'rowBtnHeight' : 40,
                    'rowBtnBorderStyle' : "solid",
                    'rowBtnBorderRadius' : 0,
                    'rowBtnShowBckgrnd' : false,
//                    'rowBtnBckgrndColorUp' : 0xf2f2f2,
                    'rowBtnLabelPlacement' : "center overlay",
                    'rowBtnLabelHalign' : "left",
                    'rowBtnLabelFontSize' : 14,
                    'rowBtnLabelHoffset' : 0,
                    'rowBtnLabelVoffset' : 20,
//                    'rowBtnLabelColorUp' : 0x5b5f65,
//                    'rowBtnLabelColorDown' : 0x5b5f65,
                    'rowBtnImgHoffset' : 0,
                    'rowBtnImgVoffset' : 20,
                    'rowShowStamp' : false,
                    'rowStampImp' : "",
                    'rowStampWidth' : 30,
                    'rowStampHeight' : 30,
                    'rowStampHoffset' : 0,
                    'rowStampVoffset' : 0,
                    'rowKantBtnLabelWidth' : 125,
                    'rowZoomHoffset' : 0,
                    'rowZoomVoffset' : 0,
//                    'zoomOverlayBckgrndColor' : 0x000000,
                    'zoomOverlayAlpha' : 80,
                    'zoomGalleryPadding' : 10,
                    'zoomGalleryHoffset' : 0,
                    'zoomGalleryVoffset' : 0,
                    'zoomCloseImp' : "",
                    'zoomCloseWidth' : 22,
                    'zoomCloseHeight' : 22,
                    'zoomCloseHoffset' : 0,
                    'zoomCloseVoffset' : 0,
                    'compCapValue' : 0,
                    'rowContainHeight' : 600,
                    'rowBckgrndShowImp' : false,
                    'rowBckgrndImpUp' : "",
                    'rowBckgrndImpDown' : "",
                    'colContainType' : "horizontal grid layout",
                    'colContainWidth' : 870,
                    'colContainHgap' : 15,
                    'colContainVgap' : 0,
                    'colContainHoffset' : 0,
                    'colContainVoffset' : 20,
                    'colContainBorderStyle' : "none",
                    'colContainBorderWidth' : 0,
//                    'colContainBorderColor' : 0xa6a8ab,
//                    'colContainBckgrndColor' : 0xffffff,
                    'tooltipWidth' : 150,
                    'tooltipBorderWidth' : 2,
//                    'tooltipBorderColor' : 0xa6a8ab,
//                    'tooltipBckgrndColor' : 0xffffff,
                    'tooltipLabelHalign' : "left",
                    'tooltipFontSize' : 18,
//                    'tooltipFontColor' : 0x5b5f65,
                    'zoomImp' : "",
                    'zoomWidth' : 20,
                    'zoomHeight' : 20,
                    'colZoomHoffset' : 0,
                    'colZoomVoffset' : 0,
                    'zoomBorderWidth' : 1,
//                    'zoomBorderColor' : 0xa6a8ab,
//                    'zoomBckgrndColor' : 0xffffff,
                    'rowContainSetRowPer' : 3,
                    'rowContainScrlEndPos' : 150,
                    'rowContainChldInitAlpha' : 100,
                    'rowContainChldEndAlpha' : 0,
                    'rowContainAutoNext' : true,
                    'colBtnDefaultType' : "Base",
                    'colBtnWidth' : 44,
                    'colBtnHeight' : 44,
                    'colBtnBorderStyle' : "none",
                    'colBtnBorderRadius' : 2,
                    'colBtnShowBckgrnd' : true,
                    'colRadShowImp' : true,
                    'colChkShowImp' : true,
//                    'colBtnBckgrndColorUp' : 0xffffff,
//                    'colBtnBckgrndColorOver' : 0xf2f2f2,
//                    'colBtnBckgrndColorDown' : 0xffbd1a,
                    'colBtnShowLabel' : false,
                    'colBtnLabelPlacement' : "bottom",
                    'colBtnLabelHalign' : "center",
                    'colBtnLabelFontSize' : 14,
                    'colBtnLabelHoffset' : 0,
                    'colBtnLabelVoffset' : 0,
//                    'colBtnLabelColorUp' : 0x5b5f65,
//                    'colBtnLabelColorOver' : 0x5b5f65,
//                    'colBtnLabelColorDown' : 0x5b5f65,
                    'colBtnImgHoffset' : 0,
                    'colBtnImgVoffset' : 0,
                    'colShowStamp' : false,
                    'colStampImp' : "",
                    'colStampWidth' : 30,
                    'colStampHeight' : 30,
                    'colStampHoffset' : 0,
                    'colStampVoffset' : 0,
                    'colKantBtnLabelWidth' : 100,
                    'colRadChckLabelWidth' : 150,
                    'colOtherInitTxt' : "",
                    'colOtherMinVal' : 1,
                    'colOtherMaxVal' : 100,
                    'colOtherMsgWidth' : 100,
                    'colBtnMouseOverDownShadow' : false,
                    'colBtnMouseOverBounce' : false,
                    'colBtnMouseOverScale' : 100,
                    'colBtnMouseDownScale' : 100,
                    'colBtnMouseDownAlpha' : 100,
                    'colBtnUseTooltip' : false,
                    'colBtnUseZoom' : false,
                    'compClickType' : "rating",
                    'colBtnPadding' : 5,
                    'colBtnBorderWidthUp' : 2,
                    'colBtnBorderWidthOver' : 2,
                    'colBtnBorderWidthDown' : 4,
                    'compContainPos' : "relative",
                    'compRTL' : false,
                    'rowContainAutoWidth' : true,
                    'rowContainAutoHeight' : true,
                    'rowContainBckgrndDispType' : "none",
                    'rowContainImgImport' : "",
                    'rowContainImgImportHoffset' : 0,
                    'rowContainImgImportVoffset' : 0,
                    'rowContainShowLabel' : false,
                    'rowContainLabelHalign' : "left",
                    'rowContainLabelFontSize' : 18,
                    'rowContainLabelPadding' : 4,
//                    'rowContainLabelColor' : 0x5b5f65,
                    'rowBtnPadding' : 10,
                    'rowBtnBorderWidthUp' : 2,
                    'rowBtnBorderWidthDown' : 2,
//                    'rowBtnBorderColorUp' : 0xa6a8ab,
//                    'rowBtnBorderColorDown' : 0x5b5f65,
                    'rowBtnLabelOvrWidth' : false,
                    'rowBtnLabelWidth' : 100,
                    'rowBtnLabelOverlayShowBckgrnd' : false,
//                    'rowBtnLabelOverlayBckgrndColor' : 0xffffff,
                    'rowBtnLabelOverlayPadding' : 4,
                    'rowTxtBtnAdjustHeightType' : "none",
                    'zoomActionType' : "click append image",
                    'zoomGalleryBorderStyle' : "none",
                    'zoomGalleryBorderWidth' : 0,
//                    'zoomGalleryBorderColor' : 0xa6a8ab,
                    'colContainHeight' : 400,
                    'colContainPadding' : 0,
                    'colContainBckgrndDispType' : "none",
                    'colContainImgImport' : "",
                    'colContainImgImportHoffset' : 0,
                    'colContainImgImportVoffset' : 0,
                    'colContainShowLabel' : false,
                    'colContainLabelHalign' : "left",
                    'colContainLabelFontSize' : 18,
                    'colContainLabelPadding' : 4,
//                    'colContainLabelColor' : 0x5b5f65,
                    'rowContainScrlAnimSpeed' : 500,
                    'rowContainChldEnableAlpha' : 50,
                    'rowContainGoOpaque' : false,
                    'colContainShowTopLabelHeader' : false,
//                    'colBtnBorderColorUp' : 0xd2d3d5,
//                    'colBtnBorderColorOver' : 0xa6a8ab,
//                    'colBtnBorderColorDown' : 0xffbd1a,
                    'colBtnLabelOvrWidth' : false,
                    'colBtnLabelWidth' : 125,
                    'colBtnLabelOverlayShowBckgrnd' : false,
//                    'colBtnLabelOverlayBckgrndColor' : 0xffffff,
                    'colBtnLabelOverlayPadding' : 4,
                    'colTxtBtnAdjustHeightType' : "none",
                    'colRadChckLabelHalign' : "left",
                    'colRadChckLabelFontSize' : 14,
//                    'colRadChckLabelColorUp' : 0x5b5f65,
//                    'colRadChckLabelColorOver' : 0x5b5f65,
//                    'colRadChckLabelColorDown' : 0x5b5f65,
                    'colRadChckLabelHoffset' : 0,
                    'colRadChckLabelVoffset' : 5,
                    'colKntrInputTxtAreaWidth' : 125,
                    'colKntrInputLabelHalign' : "left",
                    'colKntrInputLabelWidth' : 150,
                    'colKntrInputLabelHoffset' : 0,
                    'colKntrInputLabelVoffset' : 5,
                    'colKntrInputLabelFontSize' : 18,
//                    'colKntrInputLabelColorUp' : 0x5b5f65,
//                    'colKntrInputLabelColorOver' : 0x5b5f65,
//                    'colKntrInputLabelColorDown' : 0x5b5f65,
                    'colOtherInputHalign' : "left",
                    'colOtherInputFontSize' : 16,
//                    'colOtherInputColor' : 0x5b5f65,
                    'colContainOptValign' : "middle"
                }
        }
}