/**
 * qcslidermatrix class
 * Inherits from SESurveyTool
 */
function qcslidermatrix(questionContainers, json, globalOpts) {
    SESurveyTool.prototype.init.call(this, questionContainers, json, globalOpts);
	this.singlePunchCount = 0;
}
qcslidermatrix.prototype = Object.create(SESurveyTool.prototype);
qcslidermatrix.prototype.type = function(){
    return "qcslidermatrix";
}
qcslidermatrix.prototype.slidertype = function() {
    return this.slidertype;
}
qcslidermatrix.prototype.getDependencies = function(){
    return [
        {'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcomponent/SliderMatrix/SliderMatrix.js'}
        //{'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcore/QFactory.js'},
		//{'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcore/QContainer.js'},
		//{'type':'script', 'url' : surveyPage.path + 'lib/qstudio/qcreator/qcore/QWidget.js'} 
    ];
}
qcslidermatrix.prototype.setInitialResponses = function (){
 
var dimResp = [];
    $.each(this.subquestions, function(rowid, e) {
        var colResp = [];
        $.each(e.inputs.filter(":checked"), function(i, e1) {
            colResp.push({index:$(e1).attr("colid")});
        });
        dimResp.push({rowIndex: rowid, colIndex:colResp});
    });
    this.component.setDimenResp(dimResp);
}
qcslidermatrix.prototype.setResponses = function (){
    var response = this.getResponse();
    if (response == null) return;
    this.clearInputs(); // need to clear the responses before setting them.
    var that = this;
    $.each($(response.Value), function(i,e) { // Sets categories

	var punchID = that.inputs[response[e].columnValue].value
	if(typeof surveyPlatform != "undefined" && surveyPlatform=="Nfield"){     // This code belongs to Nfield
		var splitRowVal = e.split('-');
		var splitColVal = punchID.split('-');
		punchID = splitRowVal[0] +"-"+splitColVal[1];
	}
	var inputs = that.subquestions[i].inputs;
        var multi = inputs.filter('input[type=checkbox]');
		
        if (multi) inputs.filter('[value='+punchID+']').val($.makeArray(punchID));
        else inputs.val($.makeArray(punchID));
    });
}
qcslidermatrix.prototype.build = function(){
            this.component = new SliderMatrix();
			var finalparams=this.params();
			var rowArray = [],
            colArray = [],
            that = this;

        // Create questions and columns to build
        this.buildArraysFromGrid();

        // Build up row array
        $.each(this.subquestions, function (i, e) {
            var label = e.label;
            label.find('span').removeClass('mrQuestionText');
			label.find("span").removeClass('mrSingleText');
            label.find("span").removeClass('mrMultipleText');
			if(typeof surveyPlatform=="undefined"){      // This code belongs to Dimensions
				var rowId = e.id;
			}else if(surveyPlatform=="Nfield"){     // This code belongs to Nfield
				var subqid=e.inputs.filter('input[type!=text]').eq(0).attr("value");
				subqid=subqid.split("-");
				var rowId = subqid[0]+'-'+e.id;
			}
            rowArray.push({
                id: rowId,
                label: label.html(),
                description: label.text(),
                image: e.image
            });
        });

        // Build up column array
        $.each(this.columnheaders, function (i, e) {
            var label = $(e.label);
            label.find('span').removeClass('mrQuestionText');
			label.find("span").removeClass('mrSingleText');
            label.find("span").removeClass('mrMultipleText');
            label.find("span").attr('style','');
            
            var image = label.find('img');
			image.hide();
			//alert($(that.subquestions[0].inputs[i]).val() +"-->"+ label.text());
			colArray.push({
                id: $(that.subquestions[0].inputs[i]).val(),
                label: label.html(),
                description: label.text(),
                image: image.attr('src'),
                isRadio: $(that.subquestions[0].inputs[i]).attr('isexclusive') == "true"
            });

            if (colArray[colArray.length-1].isRadio) {
                colArray[colArray.length-1].type = 'radiocheck';  // radio button
            }
        });
				
        
        this.component.rowArray(rowArray);
        this.component.columnArray(colArray);
        this.component.baseTool="slidermatrix";
		this.component.params(finalparams);
        this.deferred.resolve();
}
qcslidermatrix.prototype.toolOptions = function() {
        $.extend(this.options, eval("this.options."+qcslidermatrix.prototype.type()));
		switch(pageLayout.deviceType.toUpperCase()) {
            case "LARGETABLET":
            case "MEDIUMTABLET":
            case "SMALLTABLET":
            case "SMARTPHONETOUCH":
			    if(this.orientation==0||this.orientation==180) 
                return  {
						'compQuestionType': "Single Choice",
						'rowContainType': "grid layout",
						'rowBtnUseZoom': true,
						'rowContainLabel': "",
						'rowBtnShowLabel': true,
						'rowBtnUseTooltip': false,
						'rowContainWidth': 850,
						'rowContainPadding': 0,
						'rowContainHgap': 0,
						'rowContainVgap': 20,
						'rowContainHoffset': 0,
						'rowContainVoffset': 0,
						'rowBtnDefaultType': "Label only",
						'rowBtnWidth': 50,
						'rowBtnHeight': 100,
						'rowBtnBorderStyle': "solid",
						'rowBtnBorderRadius': 5,
						'rowBtnLabelPlacement': "bottom",
						'rowBtnLabelHalign': "right",
						'rowBtnLabelFontSize': 18,
						'rowBtnLabelHoffset': 0,
						'rowBtnLabelVoffset': 75,
//						'rowBtnLabelColorUp': 0x333333,
//						'rowBtnLabelColorDown': 0x333333,
						'rowBtnImgHoffset': 0,
						'rowBtnImgVoffset': 0,
						'rowShowStamp': false,
						'rowStampWidth': 30,
						'rowStampHeight': 30,
						'rowStampHoffset': 0,
						'rowStampVoffset': 0,
						'rowKantBtnLabelWidth': 100,
						'rowZoomHoffset': 0,
						'rowZoomVoffset': 0,
//						'zoomOverlayBckgrndColor': 0x000000,
						'zoomOverlayAlpha': 88,
						'zoomGalleryPadding': 10,
						'zoomGalleryHoffset': 0,
						'zoomGalleryVoffset': 0,
						'zoomCloseWidth': 22,
						'zoomCloseHeight': 22,
						'zoomCloseHoffset': 0,
						'zoomcloseVoffset': 0,
						'rowContainHeight': 300,
						'rowbckgrndshowImp': false,
						'rowbckgrndImpup': "",
						'rowbckgrndImpdown': "",
						'colContaintype': "grid layout",
						'colContainWidth': 600,
						'colContainhgap': 20,
						'colContainvgap': 20,
						'colContainhoffset': 0,
						'colContainVoffset': 0,
						'colContainBorderstyle': "solid",
						'colContainBorderWidth': 0,
//						'colContainBorderColor': 0xcccccc,
//						'colContainbckgrndColor': 0xFFFFFF,
						'tooltipWidth': 100,
						'tooltipBorderWidth': 1,
//						'tooltipBorderColor': 0xcccccc,
//						'tooltipbckgrndColor': 0xf5f5f5,
						'tooltipLabelhalign': "left",
						'tooltipFontSize': 12,
//						'tooltipFontColor': 0x555555,
						'zoomWidth': 20,
						'zoomHeight': 20,
						'colzoomhoffset': 0,
						'colzoomVoffset': 0,
						'zoomBorderWidth': 1,
//						'zoomBorderColor': 0xcccccc,
//						'zoombckgrndColor': 0xf5f5f5,
						'rowContainsetrowper': 3,
						'rowContainscrlendpos': -300,
						'rowContainchldinitalpha': 100,
						'rowContainchldendalpha': 100,
						'rowContainautonext': false,
						'colBtndefaulttype': "Base",
						'colBtnWidth': 125,
						'colBtnHeight': 100,
						'colBtnBorderstyle': "solid",
						'colBtnBorderradius': 5,
						'colBtnshowbckgrnd': true,
						'colradshowImp': false,
						'colchkshowImp': false,
//						'colBtnbckgrndColorup': 0xf5f5f5,
//						'colBtnbckgrndColorover': 0xcccccc,
//						'colBtnbckgrndColordown': 0xd9560b,
						'colradImpup': "",
						'colradImpover': "",
						'colradImpdown': "",
						'colchkImpup': "",
						'colchkImpover': "",
						'colchkImpdown': "",
						'colBtnshowLabel': true,
						'colBtnLabelplacement': "bottom",
						'colBtnLabelhalign': "left",
						'colBtnLabelFontSize': 15,
						'colBtnLabelhoffset': 0,
						'colBtnLabelVoffset': 0,
//						'colBtnLabelColorup': 0x555555,
//						'colBtnLabelColorover': 0x000000,
//						'colBtnLabelColordown': 0xff0000,
						'colBtnImghoffset': 0,
						'colBtnImgVoffset': 0,
						'colshowStamp': false,
						'colStampWidth': 30,
						'colStampHeight': 30,
						'colStamphoffset': 0,
						'colStampVoffset': 0,
						'colkantBtnLabelWidth': 100,
						'colRadChckLabelWidth': 100,
						'colRadChckWidthradio': 30,
						'colRadChckHeightradio': 30,
						'colRadChckWidthcheck': 30,
						'colRadChckHeightcheck': 30,
						'colotherinittxt': "Please specify...",
						'colotherminval': 1,
						'colothermaxval': 100,
						'colothermsgWidth': 100,
						'colotherinvalidmsg': "Number is invalid",
						'colotherrangemsg': "Number must be >= min & <= max",
						'colBtnmouseoverdownshadow': true,
						'colBtnmouseoverbounce': true,
						'colBtnmouseoverscale': 100,
						'colBtnmousedownscale': 100,
						'colBtnmousedownalpha': 100,
						'colBtnusetooltip': false,
						'colBtnusezoom': true,
						'rowContainShowBckgrnd': false,
//						'rowBtnLabelbckgrndColor': 0xf2f2f2,
						'rowtxtBtnbckgrndtrim': false,
						'zoomgallerymaxWidth': 500,
						'zoomgallerymaxHeight': 500,
						'rowContainpos': "relative",
						'colContainshowbckgrnd': false,
						'colBtnBorderWidth': 1,
//						'colBtnLabelbckgrndColor': 0xf2f2f2,
						'coltxtBtnbckgrndtrim': false,
						'colSldrImgDispType': "right",
//						'rowBtnBckgrndColorDown': 0xfce6c9,
						'colContainLabel': "",
						'rowContainBorderstyle': "solid",
						'rowContainBorderWidth': 0,
//						'rowContainBorderColor': 0xcccccc,
//						'rowContainbckgrndColor': 0xf5f5f5,
						'rowBtnBorderWidth': 1,
//						'rowBtnBorderColor': 0xcccccc,
						'rowBtnshowbckgrnd': false,
//						'rowBtnBckgrndColorUp': 0xf5f5f5,
						'rowBtnLabelPadding': 2,
						'rowBtnImgPadding': 5,
						'rowContainScrlInitPos': 500,
						'rowContainScrlDispPos': 220,
						'rowContainChildOpaq': 100,
//						'colBtnBorderColor': 0xcccccc,
						'colBtnImgPadding': 5,
						'colBtnLabelPadding': 2,
						'colSldrHndleLabDispType': "column Label",
						'colSldrHndleShowImp': false,
						'colSldrDirection': "horizontal",
						'colSldrMinVal': 0,
						'colSldrMaxVal': 100,
						'colSldrPrecVal': 0,
						'colSldrTrackWidth': 350,
						'colSldrTrackHeight': 15,
						'colSldrTrackBorderStyle': "solid",
						'colSldrTrackBorderWidth': 5,
						'colSldrTrackBorderRadius': 0,
//						'colSldrTrackBorderColor': 0xcccccc,
//						'colSldrTrackColor': 0xf5f5f5,
						'colSldrTrackShowImp': false,
						'colSldrTrackImp': "",
						'colSldrshowHighlight': true,
//						'colSldrHighlightColor':0x333333,
						'colSldrTickWidth': 1,
						'colSldrTickHeight': 10,
//						'colSldrTickColor': 0x333333,
						'colSldrTickLabDispType': "show all",
						'colSldrTickLabWidth': 50,
						'colSldrTickLabOffset': 5,
						'colSldrTickLabFontSize': 14,
//						'colSldrTickLabColor': 0x333333,
						'colSldrHndleInitLoc': 0,
						'colSldrHndleWidth': 25,
						'colSldrHndleHeight': 30,
						'colSldrHndleBorderStyle': "solid",
						'colSldrHndleBorderWidth': 2,
						'colSldrHndleBorderRadius': 0,
//						'colSldrHndleColorUp': 0x000000,
//						'colSldrHndleColorDown': 0x000000,
						'colSldrHndleImpUp': "",
						'colSldrHndleImpDown': "",
						'colSldrHndleLabFontSize': 11,
//						'colSldrHndleLabFontColor': 0x000000,
						'colSldrHndleLabInitTxt': "Click To Activate",
						'colSldrHndleLabWidth': 100,
						'colSldrHndleLabHoffset': 0,
						'colSldrHndleLabVoffset': 0,
						'colSldrImgContWidth': 200,
						'colSldrImgContHeight': 200,
						'colSldrImgContHoffset': 40,
						'colSldrImgContVoffset': -30,
						'colSldrShowImgCont': true,
						'colSldrImgPlacement': "right",
						'colSldrHndleSnap': false,
//						'colSldrHndleBorderColor': 0x777777,
//						'colSldrHndleBorderColorDown': 0xF37F26,
						'colSldrHndleSnapType': "none"
				}
				else
				return {
						'compQuestionType': "Single Choice",
						'rowContainType': "grid layout",
						'rowBtnUseZoom': true,
						'rowContainLabel': "",
						'rowBtnShowLabel': true,
						'rowBtnUseTooltip': false,
						'rowContainWidth': 850,
						'rowContainPadding': 0,
						'rowContainHgap': 0,
						'rowContainVgap': 20,
						'rowContainHoffset': 0,
						'rowContainVoffset': 0,
						'rowBtnDefaultType': "Label only",
						'rowBtnWidth': 50,
						'rowBtnHeight': 100,
						'rowBtnBorderStyle': "solid",
						'rowBtnBorderRadius': 5,
						'rowBtnLabelPlacement': "bottom",
						'rowBtnLabelHalign': "right",
						'rowBtnLabelFontSize': 18,
						'rowBtnLabelHoffset': 0,
						'rowBtnLabelVoffset': 75,
//						'rowBtnLabelColorUp': 0x333333,
//						'rowBtnLabelColorDown': 0x333333,
						'rowBtnImgHoffset': 0,
						'rowBtnImgVoffset': 0,
						'rowShowStamp': false,
						'rowStampWidth': 30,
						'rowStampHeight': 30,
						'rowStampHoffset': 0,
						'rowStampVoffset': 0,
						'rowKantBtnLabelWidth': 100,
						'rowZoomHoffset': 0,
						'rowZoomVoffset': 0,
//						'zoomOverlayBckgrndColor': 0x000000,
						'zoomOverlayAlpha': 88,
						'zoomGalleryPadding': 10,
						'zoomGalleryHoffset': 0,
						'zoomGalleryVoffset': 0,
						'zoomCloseWidth': 22,
						'zoomCloseHeight': 22,
						'zoomCloseHoffset': 0,
						'zoomcloseVoffset': 0,
						'rowContainHeight': 300,
						'rowbckgrndshowImp': false,
						'rowbckgrndImpup': "",
						'rowbckgrndImpdown': "",
						'colContaintype': "grid layout",
						'colContainWidth': 600,
						'colContainhgap': 20,
						'colContainvgap': 20,
						'colContainhoffset': 0,
						'colContainVoffset': 0,
						'colContainBorderstyle': "solid",
						'colContainBorderWidth': 0,
//						'colContainBorderColor': 0xcccccc,
//						'colContainbckgrndColor': 0xFFFFFF,
						'tooltipWidth': 100,
						'tooltipBorderWidth': 1,
//						'tooltipBorderColor': 0xcccccc,
//						'tooltipbckgrndColor': 0xf5f5f5,
						'tooltipLabelhalign': "left",
						'tooltipFontSize': 12,
//						'tooltipFontColor': 0x555555,
						'zoomWidth': 20,
						'zoomHeight': 20,
						'colzoomhoffset': 0,
						'colzoomVoffset': 0,
						'zoomBorderWidth': 1,
//						'zoomBorderColor': 0xcccccc,
//						'zoombckgrndColor': 0xf5f5f5,
						'rowContainsetrowper': 3,
						'rowContainscrlendpos': -300,
						'rowContainchldinitalpha': 100,
						'rowContainchldendalpha': 100,
						'rowContainautonext': false,
						'colBtndefaulttype': "Base",
						'colBtnWidth': 125,
						'colBtnHeight': 100,
						'colBtnBorderstyle': "solid",
						'colBtnBorderradius': 5,
						'colBtnshowbckgrnd': true,
						'colradshowImp': false,
						'colchkshowImp': false,
//						'colBtnbckgrndColorup': 0xf5f5f5,
//						'colBtnbckgrndColorover': 0xcccccc,
//						'colBtnbckgrndColordown': 0xd9560b,
						'colradImpup': "",
						'colradImpover': "",
						'colradImpdown': "",
						'colchkImpup': "",
						'colchkImpover': "",
						'colchkImpdown': "",
						'colBtnshowLabel': true,
						'colBtnLabelplacement': "bottom",
						'colBtnLabelhalign': "left",
						'colBtnLabelFontSize': 15,
						'colBtnLabelhoffset': 0,
						'colBtnLabelVoffset': 0,
//						'colBtnLabelColorup': 0x555555,
//						'colBtnLabelColorover': 0x000000,
//						'colBtnLabelColordown': 0xff0000,
						'colBtnImghoffset': 0,
						'colBtnImgVoffset': 0,
						'colshowStamp': false,
						'colStampWidth': 30,
						'colStampHeight': 30,
						'colStamphoffset': 0,
						'colStampVoffset': 0,
						'colkantBtnLabelWidth': 100,
						'colRadChckLabelWidth': 100,
						'colRadChckWidthradio': 30,
						'colRadChckHeightradio': 30,
						'colRadChckWidthcheck': 30,
						'colRadChckHeightcheck': 30,
						'colotherinittxt': "Please specify...",
						'colotherminval': 1,
						'colothermaxval': 100,
						'colothermsgWidth': 100,
						'colotherinvalidmsg': "Number is invalid",
						'colotherrangemsg': "Number must be >= min & <= max",
						'colBtnmouseoverdownshadow': true,
						'colBtnmouseoverbounce': true,
						'colBtnmouseoverscale': 100,
						'colBtnmousedownscale': 100,
						'colBtnmousedownalpha': 100,
						'colBtnusetooltip': false,
						'colBtnusezoom': true,
						'rowContainShowBckgrnd': false,
//						'rowBtnLabelbckgrndColor': 0xf2f2f2,
						'rowtxtBtnbckgrndtrim': false,
						'zoomgallerymaxWidth': 500,
						'zoomgallerymaxHeight': 500,
						'rowContainpos': "relative",
						'colContainshowbckgrnd': false,
						'colBtnBorderWidth': 1,
//						'colBtnLabelbckgrndColor': 0xf2f2f2,
						'coltxtBtnbckgrndtrim': false,
						'colSldrImgDispType': "right",
//						'rowBtnBckgrndColorDown': 0xfce6c9,
						'colContainLabel': "",
						'rowContainBorderstyle': "solid",
						'rowContainBorderWidth': 0,
//						'rowContainBorderColor': 0xcccccc,
//						'rowContainbckgrndColor': 0xf5f5f5,
						'rowBtnBorderWidth': 1,
//						'rowBtnBorderColor': 0xcccccc,
						'rowBtnshowbckgrnd': false,
//						'rowBtnBckgrndColorUp': 0xf5f5f5,
						'rowBtnLabelPadding': 2,
						'rowBtnImgPadding': 5,
						'rowContainScrlInitPos': 500,
						'rowContainScrlDispPos': 220,
						'rowContainChildOpaq': 100,
//						'colBtnBorderColor': 0xcccccc,
						'colBtnImgPadding': 5,
						'colBtnLabelPadding': 2,
						'colSldrHndleLabDispType': "column Label",
						'colSldrHndleShowImp': false,
						'colSldrDirection': "horizontal",
						'colSldrMinVal': 0,
						'colSldrMaxVal': 100,
						'colSldrPrecVal': 0,
						'colSldrTrackWidth': 350,
						'colSldrTrackHeight': 15,
						'colSldrTrackBorderStyle': "solid",
						'colSldrTrackBorderWidth': 5,
						'colSldrTrackBorderRadius': 0,
//						'colSldrTrackBorderColor': 0xcccccc,
//						'colSldrTrackColor': 0xf5f5f5,
						'colSldrTrackShowImp': false,
						'colSldrTrackImp': "",
						'colSldrshowHighlight': true,
//						'colSldrHighlightColor':0x333333,
						'colSldrTickWidth': 1,
						'colSldrTickHeight': 10,
//						'colSldrTickColor': 0x333333,
						'colSldrTickLabDispType': "show all",
						'colSldrTickLabWidth': 50,
						'colSldrTickLabOffset': 5,
						'colSldrTickLabFontSize': 14,
//						'colSldrTickLabColor': 0x333333,
						'colSldrHndleInitLoc': 0,
						'colSldrHndleWidth': 25,
						'colSldrHndleHeight': 30,
						'colSldrHndleBorderStyle': "solid",
						'colSldrHndleBorderWidth': 2,
						'colSldrHndleBorderRadius': 0,
//						'colSldrHndleColorUp': 0x000000,
//						'colSldrHndleColorDown': 0x000000,
						'colSldrHndleImpUp': "",
						'colSldrHndleImpDown': "",
						'colSldrHndleLabFontSize': 11,
//						'colSldrHndleLabFontColor': 0x000000,
						'colSldrHndleLabInitTxt': "Click To Activate",
						'colSldrHndleLabWidth': 100,
						'colSldrHndleLabHoffset': 0,
						'colSldrHndleLabVoffset': 0,
						'colSldrImgContWidth': 200,
						'colSldrImgContHeight': 200,
						'colSldrImgContHoffset': 40,
						'colSldrImgContVoffset': -30,
						'colSldrShowImgCont': true,
						'colSldrImgPlacement': "right",
						'colSldrHndleSnap': false,
//						'colSldrHndleBorderColor': 0x777777,
//						'colSldrHndleBorderColorDown': 0xF37F26,
						'colSldrHndleSnapType': "none"
                }
            case "PC":
            case "OTHERDEVICE":
            default:
                return {
						'compQuestionType': "Single Choice",
						'rowContainType': "grid layout",
						'rowBtnUseZoom': true,
						'rowContainLabel': "",
						'rowBtnShowLabel': true,
						'rowBtnUseTooltip': false,
						'rowContainWidth': 850,
						'rowContainPadding': 0,
						'rowContainHgap': 0,
						'rowContainVgap': 20,
						'rowContainHoffset': 0,
						'rowContainVoffset': 0,
						'rowBtnDefaultType': "Label only",
						'rowBtnWidth': 200,
						'rowBtnHeight': 100,
						'rowBtnBorderStyle': "solid",
						'rowBtnBorderRadius': 5,
						'rowBtnLabelPlacement': "bottom",
						'rowBtnLabelHalign': "right",
						'rowBtnLabelFontSize': 18,
						'rowBtnLabelHoffset': 0,
						'rowBtnLabelVoffset': 75,
//						'rowBtnLabelColorUp': 0x333333,
//						'rowBtnLabelColorDown': 0x333333,
						'rowBtnImgHoffset': 0,
						'rowBtnImgVoffset': 0,
						'rowShowStamp': false,
						'rowStampWidth': 30,
						'rowStampHeight': 30,
						'rowStampHoffset': 0,
						'rowStampVoffset': 0,
						'rowKantBtnLabelWidth': 100,
						'rowZoomHoffset': 0,
						'rowZoomVoffset': 0,
//						'zoomOverlayBckgrndColor': 0x000000,
						'zoomOverlayAlpha': 88,
						'zoomGalleryPadding': 10,
						'zoomGalleryHoffset': 0,
						'zoomGalleryVoffset': 0,
						'zoomCloseWidth': 22,
						'zoomCloseHeight': 22,
						'zoomCloseHoffset': 0,
						'zoomcloseVoffset': 0,
						'rowContainHeight': 300,
						'rowbckgrndshowImp': false,
						'rowbckgrndImpup': "",
						'rowbckgrndImpdown': "",
						'colContaintype': "grid layout",
						'colContainWidth': 600,
						'colContainhgap': 20,
						'colContainvgap': 20,
						'colContainhoffset': 0,
						'colContainVoffset': 0,
						'colContainBorderstyle': "solid",
						'colContainBorderWidth': 0,
//						'colContainBorderColor': 0xcccccc,
//						'colContainbckgrndColor': 0xFFFFFF,
						'tooltipWidth': 100,
						'tooltipBorderWidth': 1,
//						'tooltipBorderColor': 0xcccccc,
//						'tooltipbckgrndColor': 0xf5f5f5,
						'tooltipLabelhalign': "left",
						'tooltipFontSize': 12,
//						'tooltipFontColor': 0x555555,
						'zoomWidth': 20,
						'zoomHeight': 20,
						'colzoomhoffset': 0,
						'colzoomVoffset': 0,
						'zoomBorderWidth': 1,
//						'zoomBorderColor': 0xcccccc,
//						'zoombckgrndColor': 0xf5f5f5,
						'rowContainsetrowper': 3,
						'rowContainscrlendpos': -300,
						'rowContainchldinitalpha': 100,
						'rowContainchldendalpha': 100,
						'rowContainautonext': false,
						'colBtndefaulttype': "Base",
						'colBtnWidth': 125,
						'colBtnHeight': 100,
						'colBtnBorderstyle': "solid",
						'colBtnBorderradius': 5,
						'colBtnshowbckgrnd': true,
						'colradshowImp': false,
						'colchkshowImp': false,
//						'colBtnbckgrndColorup': 0xf5f5f5,
//						'colBtnbckgrndColorover': 0xcccccc,
//						'colBtnbckgrndColordown': 0xd9560b,
						'colradImpup': "",
						'colradImpover': "",
						'colradImpdown': "",
						'colchkImpup': "",
						'colchkImpover': "",
						'colchkImpdown': "",
						'colBtnshowLabel': true,
						'colBtnLabelplacement': "bottom",
						'colBtnLabelhalign': "left",
						'colBtnLabelFontSize': 15,
						'colBtnLabelhoffset': 0,
						'colBtnLabelVoffset': 0,
//						'colBtnLabelColorup': 0x555555,
//						'colBtnLabelColorover': 0x000000,
//						'colBtnLabelColordown': 0xff0000,
						'colBtnImghoffset': 0,
						'colBtnImgVoffset': 0,
						'colshowStamp': false,
						'colStampWidth': 30,
						'colStampHeight': 30,
						'colStamphoffset': 0,
						'colStampVoffset': 0,
						'colkantBtnLabelWidth': 100,
						'colRadChckLabelWidth': 100,
						'colRadChckWidthradio': 30,
						'colRadChckHeightradio': 30,
						'colRadChckWidthcheck': 30,
						'colRadChckHeightcheck': 30,
						'colotherinittxt': "Please specify...",
						'colotherminval': 1,
						'colothermaxval': 100,
						'colothermsgWidth': 100,
						'colotherinvalidmsg': "Number is invalid",
						'colotherrangemsg': "Number must be >= min & <= max",
						'colBtnmouseoverdownshadow': true,
						'colBtnmouseoverbounce': true,
						'colBtnmouseoverscale': 100,
						'colBtnmousedownscale': 100,
						'colBtnmousedownalpha': 100,
						'colBtnusetooltip': false,
						'colBtnusezoom': true,
						'rowContainShowBckgrnd': false,
//						'rowBtnLabelbckgrndColor': 0xf2f2f2,
						'rowtxtBtnbckgrndtrim': false,
						'zoomgallerymaxWidth': 500,
						'zoomgallerymaxHeight': 500,
						'rowContainpos': "relative",
						'colContainshowbckgrnd': false,
						'colBtnBorderWidth': 1,
//						'colBtnLabelbckgrndColor': 0xf2f2f2,
						'coltxtBtnbckgrndtrim': false,
						'colSldrImgDispType': "right",
//						'rowBtnBckgrndColorDown': 0xfce6c9,
						'colContainLabel': "",
						'rowContainBorderstyle': "solid",
						'rowContainBorderWidth': 0,
//						'rowContainBorderColor': 0xcccccc,
//						'rowContainbckgrndColor': 0xf5f5f5,
						'rowBtnBorderWidth': 1,
//						'rowBtnBorderColor': 0xcccccc,
						'rowBtnshowbckgrnd': false,
//						'rowBtnBckgrndColorUp': 0xf5f5f5,
						'rowBtnLabelPadding': 2,
						'rowBtnImgPadding': 5,
						'rowContainScrlInitPos': 500,
						'rowContainScrlDispPos': 220,
						'rowContainChildOpaq': 100,
//						'colBtnBorderColor': 0xcccccc,
						'colBtnImgPadding': 5,
						'colBtnLabelPadding': 2,
						'colSldrHndleLabDispType': "column Label",
						'colSldrHndleShowImp': false,
						'colSldrDirection': "horizontal",
						'colSldrMinVal': 0,
						'colSldrMaxVal': 100,
						'colSldrPrecVal': 0,
						'colSldrTrackWidth': 350,
						'colSldrTrackHeight': 15,
						'colSldrTrackBorderStyle': "solid",
						'colSldrTrackBorderWidth': 5,
						'colSldrTrackBorderRadius': 0,
//						'colSldrTrackBorderColor': 0xcccccc,
//						'colSldrTrackColor': 0xf5f5f5,
						'colSldrTrackShowImp': false,
						'colSldrTrackImp': "",
						'colSldrshowHighlight': true,
//						'colSldrHighlightColor':0x333333,
						'colSldrTickWidth': 1,
						'colSldrTickHeight': 10,
//						'colSldrTickColor': 0x333333,
						'colSldrTickLabDispType': "show all",
						'colSldrTickLabWidth': 50,
						'colSldrTickLabOffset': 5,
						'colSldrTickLabFontSize': 14,
//						'colSldrTickLabColor': 0x333333,
						'colSldrHndleInitLoc': 0,
						'colSldrHndleWidth': 25,
						'colSldrHndleHeight': 30,
						'colSldrHndleBorderStyle': "solid",
						'colSldrHndleBorderWidth': 2,
						'colSldrHndleBorderRadius': 0,
//						'colSldrHndleColorUp': 0x000000,
//						'colSldrHndleColorDown': 0x000000,
						'colSldrHndleImpUp': "",
						'colSldrHndleImpDown': "",
						'colSldrHndleLabFontSize': 11,
//						'colSldrHndleLabFontColor': 0x000000,
						'colSldrHndleLabInitTxt': "Click To Activate",
						'colSldrHndleLabWidth': 100,
						'colSldrHndleLabHoffset': 0,
						'colSldrHndleLabVoffset': 0,
						'colSldrImgContWidth': 200,
						'colSldrImgContHeight': 200,
						'colSldrImgContHoffset': 40,
						'colSldrImgContVoffset': -30,
						'colSldrShowImgCont': true,
						'colSldrImgPlacement': "right",
						'colSldrHndleSnap': false,
//						'colSldrHndleBorderColor': 0x777777,
//						'colSldrHndleBorderColorDown': 0xF37F26,
						'colSldrHndleSnapType': "none"
                }
        }
}